"""Update tables

Revision ID: 3c0f787a60ed
Revises: 0605b741f9be
Create Date: 2025-02-26 09:49:45.885858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0f787a60ed'
down_revision: Union[str, None] = '0605b741f9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('img', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('reviews', 'created_at')
    op.drop_column('books', 'img')
    # ### end Alembic commands ###
