"""Create test_db tables

Revision ID: a90c450ed35a
Revises: f312f01ff6d5
Create Date: 2025-04-04 22:00:52.211681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90c450ed35a'
down_revision: Union[str, None] = 'f312f01ff6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_ratings_id'), 'review_ratings', ['id'], unique=False)
    op.add_column('reviews', sa.Column('review_rating', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('reviews', 'review_rating')
    op.drop_index(op.f('ix_review_ratings_id'), table_name='review_ratings')
    op.drop_table('review_ratings')
    # ### end Alembic commands ###
