"""Initial_2

Revision ID: 7c9f5727bcba
Revises: bc9ec7b61248
Create Date: 2025-02-25 10:14:30.487269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9f5727bcba'
down_revision: Union[str, None] = 'bc9ec7b61248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('reviews', 'img')
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.add_column('reviews', sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'created_at')
    # ### end Alembic commands ###
