"""Create main_db tables

Revision ID: abfb1ca2cc4c
Revises: 7cf91156e921
Create Date: 2025-03-28 12:31:05.346336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abfb1ca2cc4c'
down_revision: Union[str, None] = '7cf91156e921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_rating', sa.Float(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'review_rating')
    # ### end Alembic commands ###
