"""img add to book

Revision ID: efee7e3edcb8
Revises: cde94a914861
Create Date: 2025-02-25 09:31:14.405114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'efee7e3edcb8'
down_revision: Union[str, None] = 'cde94a914861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('img', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'img')
    # ### end Alembic commands ###
